### PR TITLE
Add details on how to add Amplify into a project

### PR DESCRIPTION
**Pull request by NicolaSaunders**
As discussed at the last dev team meeting, these instructions explain how to get the Amplify front-end starter kit working in a project - please can you check it makes sense and that I haven't missed anything>

### CODE REVIEW

**Comment by simonrjones** [comment]
I've tested this on my own personal site & it seems to work well. I didn't need to copy the dist folder since running the npm build command generates all this for you. 

See this [other PR](https://github.com/studio24/amplify/pull/15) where I've added an automatically generated ZIP file we can attach to releases to enable people to easily download just the files they need. This can easily be expanded (e.g. an example standalone HTML file would be useful I think).

**Comment by NicolaSaunders** [comment]
@maries24 Following Friday's dev team meeting, I have just pushed some more changes which removes the need for having two separate Webpack config files for handling JavaScript in Amplify, and have updated the getting started instructions accordingly.

**Comment by simonrjones** [comment]
@NicolaSaunders if you and @maries24 are happy with this, I'm happy for you to merge in the PR. If you want to talk through the versioning / ZIP file package stuff I'm happy to do so. 

My only edit would be, there is no need to copy the dist folder if staff run the npm build command since it regenerates asset files.

**Review by maries24 — APPROVED** [review]
Nice one @NicolaSaunders !

I tested to make sure the webpack build works (I was wondering as the two configs have the same name) and it does.

Approved!

**Pull request merged**
