### PR TITLE
Adding automated releases & release ZIP file

### PR DESCRIPTION
**Pull request by simonrjones**
hi @NicolaSaunders - I've tested this on my [own repo](https://github.com/simonrjones/test-auto-version). If this is merged into main branch it should do the following:

* If you add certain text into comments that are merged into main (e.g. via a PR) then it will automatically create a release. Instructions on what text to add is at the bottom of the Amplify README.
* This creates a Release PR that you can then control when its merged & thus when the new release is created.
* Once this is done, it uploads a ZIP file called `amplify.zip` to the release containing all the files you need to start using Amplify. This is defined in the zip command of the [release-please.yml](https://github.com/studio24/amplify/blob/automation/.github/workflows/release-please.yml) workflow - if this needs changing I can explain how to do so.

The end result is releases in the GitHub project, an updated version.txt file, and a ZIP file containing the files you need to get started which you can link to from the location: https://github.com/studio24/amplify/releases/latest/download/amplify.zip

The only thing you'd need to do to get this working is:

* Merge this PR 
* Add a file at the root called `version.txt`
* Add the current version number you want to use (would this be 2.0.0?)
* And then create a commit with either "fix:" or "feat:" in the commit text to kick off the automated release process.

### CODE REVIEW

**Comment by simonrjones** [comment]
@NicolaSaunders can I check - I think the "Syncing tasks" section of the README is redundant? If so, we can delete this section.

**Comment by NicolaSaunders** [comment]
@simonrjones I think you are right, this has been left in from the project base template but isn't really relevant.

**Comment by simonrjones** [comment]
FYI I have implemented this on the [WordPress multi-env config](https://github.com/studio24/wordpress-multi-env-config) project if you want to see it working in practise.

**Comment by simonrjones** [comment]
Chatted to @maries24 about where would be the most useful place to store the version number in Amplify so people are aware of what version they are running? We agree something in the `assets-src` folder makes sense. 

Would it make sense for me to add a version in a comment at the top of `assets-src/styles/core.scss`? Or I could add some form of license file in the `assets-src/styles` folder? This seems to be the main important folder for the project.

It would be useful to add a short license statement too. E.g. copyright S24, licensed under MIT license.

**Comment by NicolaSaunders** [comment]
I'm not an expert, hence I have not given much feedback on this. But I thought it worth noting that there is a version number and license details already in the `package.json`. Would these not be sufficient?

**Review by maries24 — APPROVED** [review]
Expanded the docs and updated to latest main version.

**Pull request merged**
